// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDubKOsIIyTC70fz4yglkijfr4_qEXR8',
    appId: '1:843229078574:web:77f249900768f9e140abbf',
    messagingSenderId: '843229078574',
    projectId: 'fir-project-73425',
    authDomain: 'fir-project-73425.firebaseapp.com',
    storageBucket: 'fir-project-73425.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwy_qHgsJuiTZXEo1E9B76o2SSovY5UH8',
    appId: '1:843229078574:android:22f16e81b07e9c6440abbf',
    messagingSenderId: '843229078574',
    projectId: 'fir-project-73425',
    storageBucket: 'fir-project-73425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKoLMhfd06ntpFpHBrM9URHZwd1UR7reo',
    appId: '1:843229078574:ios:9ca96878e3694de540abbf',
    messagingSenderId: '843229078574',
    projectId: 'fir-project-73425',
    storageBucket: 'fir-project-73425.appspot.com',
    iosBundleId: 'com.example.ecebee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKoLMhfd06ntpFpHBrM9URHZwd1UR7reo',
    appId: '1:843229078574:ios:9ca96878e3694de540abbf',
    messagingSenderId: '843229078574',
    projectId: 'fir-project-73425',
    storageBucket: 'fir-project-73425.appspot.com',
    iosBundleId: 'com.example.ecebee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoDubKOsIIyTC70fz4yglkijfr4_qEXR8',
    appId: '1:843229078574:web:fe605bf2bbe377d640abbf',
    messagingSenderId: '843229078574',
    projectId: 'fir-project-73425',
    authDomain: 'fir-project-73425.firebaseapp.com',
    storageBucket: 'fir-project-73425.appspot.com',
  );
}
